// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-UfK31W60p3RHSRGs7KLIx49ic1MD4mo',
    appId: '1:750241954693:web:e680f50a0d0585d3b3e2ec',
    messagingSenderId: '750241954693',
    projectId: 'todo-app-f4c64',
    authDomain: 'todo-app-f4c64.firebaseapp.com',
    storageBucket: 'todo-app-f4c64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGp0J8scF3XMKzdHU-DQhYfT3lgasgDY',
    appId: '1:750241954693:android:9210dce4baaa6a13b3e2ec',
    messagingSenderId: '750241954693',
    projectId: 'todo-app-f4c64',
    storageBucket: 'todo-app-f4c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPX4M-JZ9mR7FMmMi2KC3TBSaOA66sODg',
    appId: '1:750241954693:ios:288fd9dd61a9008cb3e2ec',
    messagingSenderId: '750241954693',
    projectId: 'todo-app-f4c64',
    storageBucket: 'todo-app-f4c64.firebasestorage.app',
    iosBundleId: 'com.example.tugaskelompok2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPX4M-JZ9mR7FMmMi2KC3TBSaOA66sODg',
    appId: '1:750241954693:ios:288fd9dd61a9008cb3e2ec',
    messagingSenderId: '750241954693',
    projectId: 'todo-app-f4c64',
    storageBucket: 'todo-app-f4c64.firebasestorage.app',
    iosBundleId: 'com.example.tugaskelompok2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-UfK31W60p3RHSRGs7KLIx49ic1MD4mo',
    appId: '1:750241954693:web:cb77be4cc6524cfcb3e2ec',
    messagingSenderId: '750241954693',
    projectId: 'todo-app-f4c64',
    authDomain: 'todo-app-f4c64.firebaseapp.com',
    storageBucket: 'todo-app-f4c64.firebasestorage.app',
  );

}